### ISSUE TITLE
Example app doesn't work

### ISSUE THREAD

**Issue by Kaspik** [VivienCormier/UIImageViewModeScaleAspect#10]
Hello, so here is the video of your example app. I am not sure what's happening, but I am pretty sure that it worked few months ago.

[contentmodechange.zip](https://github.com/VivienCormier/UIImageViewModeScaleAspect/files/351717/contentmodechange.zip)

**Comment by VivienCormier** [comment]
Hey,

I fixed the issue and I published a new version (1.5) to cocoapods.
Can you tell me if it's working for you and if I can close the issue.

have nice day!

**Comment by Kaspik** [comment]
Hello, demo works, my app much better, thanks!
