### ISSUE TITLE
Image orientation support

### ISSUE THREAD

**Issue by smejkpa7** [VivienCormier/UIImageViewModeScaleAspect#4]
The animation frames are computed from size of the UIImage ignoring image orientation. Meaning if you have orientation UIImageOrientationLeft / UIImageOrientationRight, image width and height should be switched when computing the frames, right? Or the UIImage could be rotated in setter

**Comment by VivienCormier** [comment]
Hi,

If I understand correctly, you want to animate an oriented UIImage.

I suggest you to rotate the UIImageView instead of the UIImage. I didn't try yet to to manage an oriented UIImage.

Can you share me the code you use to rotate your image and I can figure out how I can process.

**Comment by smejkpa7** [comment]
Hi,

Yes, oriented UIImage, exactly.

I just figured it out using this category for rotating the image before I set it into your class - http://stackoverflow.com/questions/5427656/ios-uiimagepickercontroller-result-image-orientation-after-upload

As the result, the UIImage that I set to you class is always in UIImageOrientationUp orientation and ti works great.
